FROM --platform=linux/amd64 node:16-alpine AS runner
WORKDIR /app

# AO UTILIZAR O GITHUB ACTIONS, AS VARIÁVEIS DEVEM SER
# DECLARADAS MANUALMENTE, AO INVÉS DE OBTIDAS PELO
# .env.production

# ENV NODE_ENV development

# VARIÁVEIS DE AMBIENTE

ENV DATABASE_URL=''
ENV QUERY_BATCH_SIZE=''
ENV NEXT_PUBLIC_API_FILESERVER_STORAGE_UPLOAD=''

COPY . .

RUN yarn install --frozen-lockfile
RUN yarn prisma generate

EXPOSE 3000

ENV PORT 3000

CMD ["yarn", "dev"]